version: '3'
services:
  postgresql:
    image: 'postgres:13-alpine'
    container_name: 'think-micro-postgres'
    environment:
      POSTGRES_PASSWORD: 'notsecure'
    ports:
      - '5432:5432'
    networks:
      - think-micro-network
    volumes:
      - '~/docker-data/think-micro-postgres:/var/lib/postgresql/data'
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: 'think-micro-rmq'
    hostname: 'node1'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - think-micro-network
    volumes:
      - 'rabbitmq:/var/lib/rabbitmq'
  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:7.8.0
    container_name: filebeat
    depends_on:
      - elasticsearch
    volumes:
      - filebeat:/usr/share/filebeat/data
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /Users/lokideos/Learning/think_micro/think_sinatra_ads/log:/var/log/ads:ro
      - /Users/lokideos/Learning/think_micro/bunny_geocoder/log:/var/log/geocoder:ro
      - /Users/lokideos/Learning/think_micro/auth/log:/var/log/auth:ro
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.0
    container_name: elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.8.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
  redis:
    image: redis:5.0.8
    container_name: 'think-micro-redis'
    ports:
      - "6379:6379"
    volumes:
      - "~/docker-data/think-micro-redis/data:/data"
    networks:
      - think-micro-network

networks:
  think-micro-network:
    driver: bridge

volumes:
  postgres:
  rabbitmq:
  redis:
  filebeat:
  elasticsearch: