---
- name: Ensure required dependencies are installed
  apt:
    name:
      - apt-transport-https
      - gnupg2
      - openjdk-11-jre-headless
    state: present

- name: Add Elasticsearch apt key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elastic repository
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
    state: present
    update_cache: true