# Install ansible-galaxy 'install elastic.elasticsearch,7.9.0' before launching the playbook

- name: Elasticsearch with custom configuration
  hosts: elastic
  roles:
    - role: elastic.elasticsearch
  vars:
    es_data_dirs:
      - "/opt/elasticsearch/data"
    es_log_dir: "/opt/elasticsearch/logs"
    es_config:
      node.name: "node1"
      cluster.name: "elasticsearch-cluster"
      discovery.type: single-node
      discovery.seed_hosts: "localhost:9300"
      network.bind_host:
        - _local_
      network.host: localhost
      http.port: 9200
      transport.port: 9300
      node.data: true
      node.master: true
      bootstrap.memory_lock: true
    es_heap_size: 2g
    es_api_port: 9200