---
- hosts: elastic
  become: yes
  gather_facts: no
  roles:
    - common
  tasks:
    - name: Ensure dependencies are installed
      apt:
        name:
          - apt-transport-https
          - gnupg2
        state: present

    - name: Add Elasticsearch apt key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Kibana repository
      apt_repository:
        repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
        state: present
        update_cache: true

    - name: Install Kibana
      package:
        name: kibana
        state: present

    - name: Ensure Kibana is started and enabled at boot
      service:
        name: kibana
        state: started
        enabled: true

    - name: Copy Kibana configuration.
      template:
        src: kibana.yml.j2
        dest: /etc/kibana/kibana.yml
        owner: root
        group: root
        mode: 0644
      notify: restart kibana

  handlers:
    - name: restart kibana
      service:
        name: kibana
        state: restarted