---
- hosts: nginx
  become: yes
  gather_facts: no
  roles:
    - common
  tasks:
    - name: ensure packages are installed
      apt:
        name: nginx
    - name: ensure ads nginx config us uploaded
      copy:
        src: "nginx/ads.nginx.conf"
        dest: /etc/nginx/conf.d/ads.conf
      notify:
        - restart nginx
    - name: ensure auth nginx config us uploaded
      copy:
        src: "nginx/auth.nginx.conf"
        dest: /etc/nginx/conf.d/auth.conf
      notify:
        - restart nginx
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: reloaded