---
- hosts: ufw
  become: yes
  gather_facts: no
  roles:
    - common
  tasks:
    - name: ensure packages are installed
      apt:
        name: ufw
    - name: allow ssh connections
      shell: |
        ufw limit ssh comment 'Rate limit for openssh server'
    - name: allow connections via Nginx
      shell: |
        ufw allow 'Nginx Full'
    - name: allow connections to RMQ management
      shell: |
        ufw allow 15672
    - name: allow connections to Kibana
      shell: |
        ufw allow 5601
    - name: enable firewall
      ufw:
        state: enabled