---
- hosts: ufw_app
  become: yes
  gather_facts: no
  roles:
    - common
  tasks:
    - name: ensure packages are installed
      apt:
        name: ufw
    - name: allow ssh connections
      shell: |
        ufw limit ssh comment 'Rate limit for openssh server'
    - name: allow connections via Nginx
      shell: |
        ufw allow 'Nginx Full'
    - name: allow connections from data layer
      shell: |
        sudo ufw allow from 46.101.236.61
    - name: enable firewall
      ufw:
        state: enabled
- hosts: ufw_data
  become: yes
  gather_facts: no
  roles:
    - common
  tasks:
    - name: ensure packages are installed
      apt:
        name: ufw
    - name: allow ssh connections
      shell: |
        ufw limit ssh comment 'Rate limit for openssh server'
    - name: allow connections via Nginx
      shell: |
        ufw allow 'Nginx Full'
    - name: allow connections to RMQ management
      shell: |
        ufw allow 15672
    - name: allow connections to Kibana
      shell: |
        ufw allow 5601
    - name: allow remote connections from app servers to logstash
      shell: |
        ufw allow from 142.93.169.162 to any proto tcp port 5044
    - name: allow remote connections from app servers to postgres
      shell: |
        ufw allow from 142.93.169.162 to any proto tcp port 5432
    - name: allow remote connections from app servers to rmq
      shell: |
        ufw allow from 142.93.169.162 to any proto tcp port 5672
    - name: enable firewall
      ufw:
        state: enabled